### ISSUE TITLE
`pip` version is smaller than required

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/autopy#5]
Currently, if I use autopy in appstraction. I get a python version of `3.11.3`, but my pip is only version `22.3.1`. For `pymobiledevice3` to install correctly, I need pip versions `>=23.1`, which I can get by running `python -m pip install --upgrade pip`. I think maybe we should do this in `autopy`, or at least include an option to specify the minimum pip version as well.

**Comment by zner0L** [comment]
I realize now that `pip` can just be updated as any other package would. So we don’t actually need to change the API here. However, because we install missing packages all in one command, if pip needs to be updated, the command still fails because the other dependencies are then still installed by the old pip.

**Comment by baltpeter** [comment]
The correct thing to do here is probably to special-case `pip` as a dependency. If the user pins a certain `pip` version, we'll install that separately first.
